export const GET_CART = "GET_CART";
export const UPDATE_CART = "UPDATE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = " DELETE_FROM_CART";
export const INCREEMENT_QUANTITY = "INCREEMENT_QUANTITY";
export const DECREEMENT_QUANTITY = "DECREEMENT_QUANTITY";
