FROM node:alpine

WORKDIR /app

COPY package*.json ./

RUN npm i --silent

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . ./

RUN npm run build

COPY . ./


CMD [ "npm" , "start" ]